// Generated by CoffeeScript 1.6.2
(function() {
  var KVStore, fs, path;

  fs = require('fs');

  path = require('path');

  KVStore = (function() {
    function KVStore(filename) {
      this.filename = filename;
      this.store = require(this.filename);
    }

    KVStore.prototype.get = function(key) {
      console.log("KV " + key);
      return this.store[key];
    };

    KVStore.prototype.set = function(key, value) {
      console.log("KV " + key + " = " + value);
      this.store[key] = value;
      return this.flush();
    };

    KVStore.prototype.flush = function() {
      return fs.writeFileSync(this.filename, JSON.stringify(this.store));
    };

    return KVStore;

  })();

  module.exports = KVStore;

}).call(this);
