// Generated by CoffeeScript 1.6.2
(function() {
  var KVStore, fs, path;

  fs = require('fs');

  path = require('path');

  KVStore = (function() {
    function KVStore(filename) {
      this.filename = path.join(process.cwd(), filename);
      this.store = fs.existsSync(this.filename) ? require(this.filename) : {};
    }

    KVStore.prototype.get = function(key) {
      return this.store[key];
    };

    KVStore.prototype.set = function(key, value) {
      if (value === null) {
        delete this.store[key];
      } else {
        this.store[key] = value;
      }
      return this.flush();
    };

    KVStore.prototype.flush = function() {
      return fs.writeFileSync(this.filename, JSON.stringify(this.store));
    };

    return KVStore;

  })();

  module.exports = KVStore;

}).call(this);
