// Generated by CoffeeScript 1.6.2
(function() {
  var PluginManager, bot, config, irc, package_info, util;

  process.stdin.resume();

  process.on('SIGINT', function() {
    return bot.disconnect("Ctrl+C from console.", process.exit);
  });

  console.log("Stating bot");

  util = require('util');

  irc = require("irc");

  config = require('../config');

  package_info = require('../package');

  PluginManager = require('./plugins');

  bot = new irc.Client(config.server, config.nick, {
    channels: config.channels,
    password: config.password,
    userName: config.username,
    realName: config.realname
  });

  bot.commandList = {};

  bot.addListener("message", function(who, channel, message) {
    var args, command;

    console.log("" + who + " => " + channel + ": " + message);
    if (0 === message.indexOf(config.trigger)) {
      args = message.split(" ");
      command = args.shift().substr(config.trigger.length);
      bot.emit("command", channel, who, command, args);
      if (bot.commandList[command]) {
        return bot.emit("command:" + command, channel, who, args);
      } else {
        return bot.emit("missing_command", channel, who, command, args);
      }
    }
  });

  bot.addMissingCommandHandler = function(callback) {
    if (this.missingCommandHanlder) {
      return false;
    }
    this.missingCommandHanlder = callback;
    bot.addListener("missing_command", this.missingCommandHanlder);
    return true;
  };

  bot.removeMissingCommandHandler = function() {
    if (!this.missingCommandHanlder) {
      return false;
    }
    bot.removeListener("missing_command", this.missingCommandHanlder);
    this.missingCommandHanlder = null;
    return true;
  };

  bot.addCommand = function(command, callback) {
    if (this.commandList[command]) {
      return false;
    }
    this.commandList[command] = callback;
    this.addListener("command:" + command, callback);
    return true;
  };

  bot.removeCommand = function(command) {
    if (!this.commandList[command]) {
      return false;
    }
    this.removeListener(command, this.commandList[command]);
    delete this.commandList[command];
    return true;
  };

  bot.plugins = new PluginManager(bot, config);

}).call(this);
