// Generated by CoffeeScript 1.6.2
(function() {
  var bot, config, irc;

  process.stdin.resume();

  process.on('SIGINT', function() {
    return bot.disconnect(process.exit);
  });

  console.log("Stating bot");

  irc = require("irc");

  config = require('../config');

  bot = new irc.Client(config.server, config.nick, {
    channels: config.channels
  });

  bot.addListener("join", function(channel, who) {
    if (who !== config.nick) {
      return bot.say(channel, who + ": hi!");
    }
  });

}).call(this);
