// Generated by CoffeeScript 1.6.2
(function() {
  var GitHubApi, UrlFetcher, url_regex,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  GitHubApi = require("node-github");

  url_regex = /(https?):\/\/([-\w\.]+)+(:\d+)?(\/([\w\/_\-\.]*)?(\?\S+)?)?/;

  UrlFetcher = (function() {
    function UrlFetcher(url) {
      this.get_library = __bind(this.get_library, this);
      this.handle = __bind(this.handle, this);      this.url = url;
      this.data = {};
    }

    UrlFetcher.prototype.handle = function(func) {
      var http;

      http = this.get_library();
      return http.request(this.url, func);
    };

    UrlFetcher.prototype.get_library = function() {
      console.log(this.url);
      if (this.url.protocol === "https") {
        console.log('https');
        return require('follow-redirects').https;
      } else {
        console.log('http');
        return require('follow-redirects').http;
      }
    };

    return UrlFetcher;

  })();

  module.exports = UrlFetcher;

}).call(this);
