// Generated by CoffeeScript 1.6.3
(function() {
  var UrlDetector, url_regex;

  url_regex = /(https?):\/\/([-\w\.]+)+(:\d+)?(\/([\w\/_\-\.]*)?(\?\S+)?)?/;

  UrlDetector = {
    has_url: function(string) {
      var match;
      if (match = string.match(url_regex)) {
        return {
          url: match[0],
          protocol: match[1],
          host: match[2],
          port: match[3] || (match[1] === "https" ? "443" : "80"),
          path: "/" + match[5],
          query: match[6]
        };
      } else {
        return false;
      }
    }
  };

  module.exports = UrlDetector;

}).call(this);
