// Generated by CoffeeScript 1.6.2
(function() {
  var URL, UrlDetector, parse_url, url_regex;

  URL = require('url');

  url_regex = /https?:\/\/[^\s]+/;

  parse_url = function(possible_url) {
    var e;

    try {
      return URL.parse(possible_url);
    } catch (_error) {
      e = _error;
      if (!e instanceof ReferenceError) {
        throw e;
      }
    }
  };

  UrlDetector = {
    has_url: function(string) {
      var match;

      if (match = string.match(url_regex)) {
        return parse_url(match[0]);
      }
    }
  };

  module.exports = UrlDetector;

}).call(this);
