// Generated by CoffeeScript 1.6.3
(function() {
  var Plugin,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Plugin = (function() {
    function Plugin(bot, config) {
      this.bot = bot;
      this.config = config;
      this.waveBackOnAction = __bind(this.waveBackOnAction, this);
      this.welcomeOnJoin = __bind(this.welcomeOnJoin, this);
      this.greeterCmd = __bind(this.greeterCmd, this);
      this.teardown = __bind(this.teardown, this);
      this.setup = __bind(this.setup, this);
      this.__name = "chatty";
      this.__author = "epochwolf";
      this.__version = "v0.0.1";
      this.__listeners = {
        action: [this.waveBackOnAction],
        join: [this.welcomeOnJoin]
      };
      this.__commands = {
        hi: this.greeterCmd
      };
      this.__autoload = false;
    }

    Plugin.prototype.setup = function() {
      return console.log("Chatty plugin loaded");
    };

    Plugin.prototype.teardown = function() {
      return console.log("Chatty plugin unloaded");
    };

    Plugin.prototype.greeterCmd = function(channel, who, args) {
      return this.bot.say(channel, "Hello");
    };

    Plugin.prototype.welcomeOnJoin = function(channel, who) {
      if (who === this.config.nick) {
        return this.bot.say(channel, "Hi everyone!");
      } else {
        return this.bot.action(channel, "welcomes " + who);
      }
    };

    Plugin.prototype.waveBackOnAction = function(who, channel, message) {
      if (message === "waves") {
        return this.bot.action(channel, "waves back");
      }
    };

    return Plugin;

  })();

  module.exports = Plugin;

}).call(this);
