// Generated by CoffeeScript 1.6.2
(function() {
  var GitHubApi, Plugin, issues_url, repo_url,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  GitHubApi = require("node-github");

  repo_url = /\/?([^\/]+)\/([^\/]+)/;

  issues_url = /\/?([^\/]+)\/([^\/]+)\/issues\/(\d+)/;

  Plugin = (function() {
    function Plugin(bot, config) {
      this.bot = bot;
      this.config = config;
      this.linkToGithub = __bind(this.linkToGithub, this);
      this.githubDetails = __bind(this.githubDetails, this);
      this.teardown = __bind(this.teardown, this);
      this.setup = __bind(this.setup, this);
      this.__name = "github_watch";
      this.__author = "epochwolf";
      this.__version = "v0.0.1";
      this.__listeners = {
        "message_with_url:github.com": [this.githubDetails]
      };
      this.__commands = {
        gh: this.linkToGithub
      };
      this.__autoload = true;
    }

    Plugin.prototype.conn = function() {
      var github;

      github = new GitHubApi({
        version: "3.0.0",
        timeout: 5000
      });
      if (this.config.github_auth) {
        github.authenticate(this.config.github_auth);
      }
      return github;
    };

    Plugin.prototype.setup = function() {
      return console.log("github_watch plugin loaded");
    };

    Plugin.prototype.teardown = function() {
      return console.log("github_watch plugin unloaded");
    };

    Plugin.prototype.githubDetails = function(channel, who, message, url) {
      var issue_id, match, path, repo, user, _,
        _this = this;

      path = url.path;
      console.log("Github link: " + path);
      if (match = path.match(issues_url)) {
        _ = match[0], user = match[1], repo = match[2], issue_id = match[3];
        return this.conn().issues.getRepoIssue({
          user: user,
          repo: repo,
          number: issue_id
        }, function(err, data) {
          var labels, login, number, state, title, _ref;

          if (err) {
            return _this.bot.say(channel, "Hmmm... github didn't like that: " + err);
          } else {
            console.log(data);
            title = data.title, number = data.number, state = data.state;
            labels = data.labels.map(function(label) {
              return label.name;
            }).join(", ");
            login = (_ref = data.user) != null ? _ref.login : void 0;
            return _this.bot.say(channel, "#" + number + " (" + state + "): " + title + " [" + labels + "]");
          }
        });
      } else if (match = path.match(repo_url)) {
        _ = match[0], user = match[1], repo = match[2];
        return this.conn().repos.get({
          user: user,
          repo: repo
        }, function(err, data) {
          var description, forks, full_name, has_issues, has_wiki, homepage, name, open_issues, stars;

          if (err) {
            return _this.bot.say(channel, "Hmmm... github didn't like that: " + err);
          } else {
            console.log(data);
            name = data.name, full_name = data.full_name, description = data.description, open_issues = data.open_issues, homepage = data.homepage, has_issues = data.has_issues, has_wiki = data.has_wiki;
            forks = data.forks_count;
            stars = data.watchers_count;
            return _this.bot.say(channel, "" + full_name + " (" + stars + "★ " + forks + "♆ " + open_issues + "☤) : " + description);
          }
        });
      }
    };

    Plugin.prototype.linkToGithub = function(channel, who, args) {
      var project, username;

      username = args[0], project = args[1];
      return this.bot.say(channel, "https://github.com/" + username + "/" + project);
    };

    return Plugin;

  })();

  module.exports = Plugin;

}).call(this);
