// Generated by CoffeeScript 1.6.2
(function() {
  var Plugin,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Plugin = (function() {
    function Plugin(bot, config) {
      this.bot = bot;
      this.config = config;
      this.sayCmd = __bind(this.sayCmd, this);
      this.teardown = __bind(this.teardown, this);
      this.setup = __bind(this.setup, this);
      this.__name = "say";
      this.__author = "epochwolf";
      this.__version = "v0.0.1";
      this.__commands = {
        say: this.sayCmd
      };
      this.__autoload = true;
    }

    Plugin.prototype.setup = function() {
      return console.log("Say plugin loaded");
    };

    Plugin.prototype.teardown = function() {
      return console.log("Say plugin unloaded");
    };

    Plugin.prototype.sayCmd = function(channel, who, args) {
      var me, me_command, message, say_channel;

      say_channel = args.shift();
      if (say_channel === ".") {
        say_channel = channel;
      }
      me_command = args.shift();
      me = me_command === "/me";
      if (!me) {
        args.unshift(me_command);
      }
      message = args.join(" ");
      if (me) {
        return this.bot.action(say_channel, message);
      } else {
        return this.bot.say(say_channel, message);
      }
    };

    return Plugin;

  })();

  module.exports = Plugin;

}).call(this);
