// Generated by CoffeeScript 1.6.2
(function() {
  var ACCEPTABLE_MIMES, Plugin, STATUS_CODES, TITLE_REGEX, UrlFetcher, bytesToSize,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  UrlFetcher = require('../url_fetcher');

  ACCEPTABLE_MIMES = /(text|html|xml)/;

  TITLE_REGEX = /<title>(.*?)<\/title>/;

  STATUS_CODES = {
    "200": "200 OK",
    "301": "301 Moved Permanently",
    "302": "302 Found",
    "307": "307 Temporary Redirect",
    "308": "308 Permanent Redirect",
    "401": "401 Unauthorized",
    "403": "403 Forbidden",
    "404": "404 Not Found",
    "405": "405 Method Not Allowed",
    "420": "420 Rate Limited",
    "422": "422 Unprocessable Entity",
    "500": "500 Internal Server Error",
    "502": "502 Bad Gateway",
    "503": "503 Service Unavailable",
    "504": "504 Gateway Timeout",
    "509": "509 Bandwidth Limit Exceeded"
  };

  bytesToSize = function(bytes) {
    var i, sizes;

    sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    if (bytes === 0) {
      return 'n/a';
    }
    i = parseInt(Math.floor(Math.log(bytes) / Math.log(1024)));
    return Math.round(bytes / Math.pow(1024, i), 2) + ' ' + sizes[[i]];
  };

  Plugin = (function() {
    function Plugin(bot, config) {
      this.bot = bot;
      this.config = config;
      this.urlDetails = __bind(this.urlDetails, this);
      this.teardown = __bind(this.teardown, this);
      this.setup = __bind(this.setup, this);
      this.__name = "url_watch";
      this.__author = "epochwolf";
      this.__version = "v0.0.1";
      this.__listeners = {
        "message_with_url": [this.urlDetails]
      };
      this.__commands = {};
      this.__autoload = true;
      this.rate_limiter = new (require('../rate_limiter'))(30 * 60);
    }

    Plugin.prototype.setup = function() {
      return console.log("url_watch plugin loaded");
    };

    Plugin.prototype.teardown = function() {
      return console.log("url_watch plugin unloaded");
    };

    Plugin.prototype.urlDetails = function(channel, who, message, url) {
      var host, request, _ref,
        _this = this;

      _ref = url, url = _ref.url, host = _ref.host;
      if (!this.rate_limiter.okay(url)) {
        return;
      }
      request = new UrlFetcher(url).handle(function(res) {
        var content_type, data, length, status_code;

        status_code = res.statusCode;
        content_type = res.headers['content-type'];
        length = res.headers['content-length'];
        data = "";
        res.on('end', function() {
          var display_status, title;

          display_status = STATUS_CODES["" + status_code] || status_code;
          title = ("" + content_type).match(ACCEPTABLE_MIMES) ? ("" + data).match(TITLE_REGEX)[1] : void 0;
          if (title) {
            return _this.bot.say(channel, "Url | " + display_status + " (" + content_type + ") | " + (title.replace(/&amp;/, "&")));
          } else if (length) {
            return _this.bot.say(channel, "Url | " + display_status + " (" + content_type + ") | " + (bytesToSize(length)));
          } else {
            return _this.bot.say(channel, "Url | " + display_status + " (" + content_type + ") | unknown size");
          }
        });
        return res.on('data', function(d) {
          data += d;
          if (data.length > 400000) {
            return res.socket.end();
          }
        });
      });
      request.end();
      return request.on('error', function(e) {
        return console.error(e);
      });
    };

    return Plugin;

  })();

  module.exports = Plugin;

}).call(this);
