// Generated by CoffeeScript 1.6.2
(function() {
  var ACCEPTABLE_MIMES, Plugin, STATUS_CODES, TITLE_REGEX, UrlDetector, UrlFetcher, bytesToSize, is_redirect,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  UrlFetcher = require('../url_fetcher');

  UrlDetector = require('../url_detector');

  ACCEPTABLE_MIMES = /(text|html|xml)/;

  TITLE_REGEX = /<title>(.*?)<\/title>/;

  STATUS_CODES = require("http").STATUS_CODES;

  bytesToSize = function(bytes) {
    var i, sizes;

    sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    if (bytes === 0) {
      return 'n/a';
    }
    i = parseInt(Math.floor(Math.log(bytes) / Math.log(1024)));
    return Math.round(bytes / Math.pow(1024, i), 2) + ' ' + sizes[[i]];
  };

  is_redirect = function(res, url) {
    var possible_new_url;

    possible_new_url = "" + res.req._headers.host + res.req.path;
    if (("" + url.host + url.path) !== possible_new_url) {
      return possible_new_url;
    }
  };

  Plugin = (function() {
    function Plugin(bot, config) {
      this.bot = bot;
      this.config = config;
      this.urlDetails = __bind(this.urlDetails, this);
      this.teardown = __bind(this.teardown, this);
      this.setup = __bind(this.setup, this);
      this.__name = "url_watch";
      this.__author = "epochwolf";
      this.__version = "v0.0.1";
      this.__listeners = {
        "message_with_url": [this.urlDetails]
      };
      this.__commands = {};
      this.__autoload = true;
      this.rate_limiter = new (require('../rate_limiter'))(30 * 60);
    }

    Plugin.prototype.setup = function() {
      return console.log("url_watch plugin loaded");
    };

    Plugin.prototype.teardown = function() {
      return console.log("url_watch plugin unloaded");
    };

    Plugin.prototype.urlDetails = function(channel, who, message, url) {
      var request,
        _this = this;

      console.log("I see: " + url.href);
      if (!this.rate_limiter.okay("" + url.host + url.path)) {
        return;
      }
      request = new UrlFetcher(url).handle(function(res) {
        var content_type, data, length, new_url, redirect_url, status_code;

        status_code = res.statusCode;
        content_type = res.headers['content-type'];
        content_type = ("" + content_type).replace(/;.*/, "");
        length = res.headers['content-length'];
        data = "";
        if (new_url = is_redirect(res, url)) {
          if (redirect_url = UrlDetector.has_url("http://" + new_url)) {
            _this.bot.emit("message_with_url:" + redirect_url.hostname, channel, who, message, redirect_url);
          }
        }
        res.on('end', function() {
          var display_status, title, title_text;

          display_status = STATUS_CODES["" + status_code] || status_code;
          title = ("" + content_type).match(ACCEPTABLE_MIMES) ? ("" + data).match(TITLE_REGEX) : void 0;
          title_text = title && title[1] ? ("" + title[1]).replace(/&amp;/, "&") : length ? "" + (bytesToSize(length)) + " " + content_type : "?? KB " + content_type;
          if (new_url) {
            title_text += " | " + new_url;
          }
          if (("" + status_code) !== "200") {
            title_text += " (" + display_status + ")";
          }
          return _this.bot.say(channel, "Web | " + title_text);
        });
        return res.on('data', function(d) {
          data += d;
          if (data.length > 40000) {
            return res.socket.end();
          }
        });
      });
      request.end();
      return request.on('error', function(e) {
        return console.error(e);
      });
    };

    return Plugin;

  })();

  module.exports = Plugin;

}).call(this);
